window.ARABIC_VISUALS = {
  words: {
    b001: { src: "img/manypixels/message_received.svg", alt: "인사 메시지 일러스트" },
    b002: { src: "img/basic/good.svg", alt: "감사 표현 카드" },
    b003: { src: "img/basic/yes.svg", alt: "네 예 카드" },
    b004: { src: "img/basic/no.svg", alt: "아니요 카드" },
    b005: { src: "img/irasutoya/water.png", alt: "물 한 잔 일러스트" },
    b006: { src: "img/irasutoya/house.png", alt: "집 일러스트" },
    b007: { src: "img/irasutoya/book.png", alt: "책 일러스트" },
    b008: { src: "img/undraw/calendar.svg", alt: "날짜 일러스트" },
    b009: { src: "img/irasutoya/morning.png", alt: "아침 일러스트" },
    b010: { src: "img/irasutoya/night.png", alt: "밤 일러스트" },
    b011: { src: "img/irasutoya/food.png", alt: "음식 일러스트" },
    b012: { src: "img/irasutoya/family.png", alt: "가족 일러스트" },
    b013: { src: "img/undraw/friendship.svg", alt: "친구 일러스트" },
    b014: { src: "img/numbers/one.svg", alt: "숫자 1 카드" },
    b015: { src: "img/numbers/two.svg", alt: "숫자 2 카드" },
    b016: { src: "img/numbers/three.svg", alt: "숫자 3 카드" },
    b017: { src: "img/colors/red.svg", alt: "빨간색 카드" },
    b018: { src: "img/colors/blue.svg", alt: "파란색 카드" },
    b019: { src: "img/colors/green.svg", alt: "초록색 카드" },
    b020: { src: "img/colors/white.svg", alt: "흰색 카드" },

    n001: { src: "img/undraw/personal_text.svg", alt: "이름 카드 일러스트" },
    n002: { src: "img/undraw/personal_text.svg", alt: "이름 카드 일러스트" },
    n003: { src: "img/undraw/personal_text.svg", alt: "이름 카드 일러스트" },
    n004: { src: "img/undraw/personal_text.svg", alt: "이름 카드 일러스트" },
    n005: { src: "img/flags/iq.svg", alt: "이라크 국기" },
    n006: { src: "img/flags/lb.svg", alt: "레바논 국기" },
    n007: { src: "img/flags/iq.svg", alt: "이라크 국기" },
    n008: { src: "img/flags/kr.svg", alt: "대한민국 국기" },

    pr001: { src: "img/undraw/personal_text.svg", alt: "자기소개 일러스트" },
    pr002: { src: "img/undraw/personal_text.svg", alt: "사람 소개 일러스트" },
    pr003: { src: "img/undraw/personal_text.svg", alt: "사람 소개 일러스트" },
    pr004: { src: "img/undraw/personal_text.svg", alt: "사람 소개 일러스트" },
    pr005: { src: "img/undraw/personal_text.svg", alt: "사람 소개 일러스트" },

    v001: { src: "img/irasutoya/student_boy.png", alt: "남학생 일러스트" },
    v002: { src: "img/irasutoya/student_girl.png", alt: "여학생 일러스트" },
    v003: { src: "img/basic/yes.svg", alt: "네 예 카드" },
    v004: { src: "img/basic/question.svg", alt: "질문 카드" },
    v005: { src: "img/undraw/travel.svg", alt: "장소 질문 일러스트" },
    v006: { src: "img/undraw/travel.svg", alt: "출발지 일러스트" },
    v007: { src: "img/basic/question.svg", alt: "질문 카드" },
    v008: { src: "img/undraw/calendar.svg", alt: "오늘 날짜 일러스트" },

    dv001: { src: "img/basic/good.svg", alt: "좋은 상태 카드" },
    dv002: { src: "img/irasutoya/sunny.png", alt: "맑은 날씨 일러스트" },
    dv003: { src: "img/basic/question.svg", alt: "상태 질문 카드" },
    dv004: { src: "img/basic/good.svg", alt: "좋음 카드" },
    dv005: { src: "img/undraw/weather_app.svg", alt: "쾌청한 날씨 일러스트" },
    dv006: { src: "img/undraw/calendar.svg", alt: "오후 시간 일러스트" },
    dv007: { src: "img/irasutoya/sunny.png", alt: "빛 일러스트" },

    f001: { src: "img/family/grandfather.svg", alt: "할아버지 카드" },
    f002: { src: "img/family/grandmother.svg", alt: "할머니 카드" },
    f003: { src: "img/family/father.svg", alt: "아버지 카드" },
    f004: { src: "img/family/mother.svg", alt: "어머니 카드" },
    f005: { src: "img/family/brother.svg", alt: "형제 카드" },
    f006: { src: "img/family/sister.svg", alt: "자매 카드" },

    o001: { src: "img/irasutoya/bag.png", alt: "가방을 든 사람 일러스트" },
    o002: { src: "img/undraw/documents.svg", alt: "문서와 펜 일러스트" },
    o003: { src: "img/irasutoya/cup.png", alt: "컵 일러스트" },
    o004: { src: "img/undraw/documents.svg", alt: "책상과 문서 일러스트" },
    o005: { src: "img/irasutoya/room.png", alt: "방 일러스트" },
    o006: { src: "img/irasutoya/cinema.png", alt: "영화관 일러스트" },

    pp001: { src: "img/position/front.svg", alt: "앞에 위치 다이어그램" },
    pp002: { src: "img/position/beside.svg", alt: "옆에 위치 다이어그램" },
    pp003: { src: "img/position/under.svg", alt: "아래에 위치 다이어그램" },
    pp004: { src: "img/position/behind.svg", alt: "뒤에 위치 다이어그램" },
    pp005: { src: "img/position/on.svg", alt: "접촉해서 위에 위치 다이어그램" },
    pp006: { src: "img/position/above.svg", alt: "공중에서 위에 위치 다이어그램" },

    g001: { src: "img/manypixels/message_received.svg", alt: "환영 메시지 일러스트" },
    g002: { src: "img/manypixels/message_received.svg", alt: "인사 메시지 일러스트" },
    g003: { src: "img/undraw/travel.svg", alt: "작별 인사 일러스트" },
    g004: { src: "img/undraw/calendar.svg", alt: "다음 만남 일러스트" },
    g005: { src: "img/irasutoya/morning.png", alt: "좋은 아침 일러스트" },
    g006: { src: "img/undraw/calendar.svg", alt: "오후 인사 일러스트" },
    g007: { src: "img/undraw/celebrating.svg", alt: "축하 일러스트" },
    g008: { src: "img/undraw/friendship.svg", alt: "만남 일러스트" },
    g009: { src: "img/undraw/personal_text.svg", alt: "이름 소개 일러스트" },

    wd001: { src: "img/weekdays/saturday.svg", alt: "토요일 달력 카드" },
    wd002: { src: "img/weekdays/sunday.svg", alt: "일요일 달력 카드" },
    wd003: { src: "img/weekdays/monday.svg", alt: "월요일 달력 카드" },
    wd004: { src: "img/weekdays/tuesday.svg", alt: "화요일 달력 카드" },
    wd005: { src: "img/weekdays/wednesday.svg", alt: "수요일 달력 카드" },
    wd006: { src: "img/weekdays/thursday.svg", alt: "목요일 달력 카드" },
    wd007: { src: "img/weekdays/friday.svg", alt: "금요일 달력 카드" },
    mo001: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo002: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo003: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo004: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo005: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo006: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo007: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo008: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo009: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo010: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo011: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },
    mo012: { src: "img/undraw/calendar.svg", alt: "월 달력 일러스트" },

    sw001: { src: "img/irasutoya/spring.png", alt: "봄 일러스트" },
    sw002: { src: "img/irasutoya/summer.png", alt: "여름 일러스트" },
    sw003: { src: "img/irasutoya/autumn.png", alt: "가을 일러스트" },
    sw004: { src: "img/irasutoya/winter.png", alt: "겨울 일러스트" },
    sw005: { src: "img/undraw/weather_app.svg", alt: "추운 날씨 일러스트" },
    sw006: { src: "img/undraw/weather_app.svg", alt: "더운 날씨 일러스트" },
    sw007: { src: "img/undraw/weather_app.svg", alt: "좋은 날씨 일러스트" },
    sw008: { src: "img/undraw/weather_app.svg", alt: "따뜻한 날씨 일러스트" },
    sw009: { src: "img/undraw/weather_app.svg", alt: "흐린 날씨 일러스트" },
    sw010: { src: "img/irasutoya/sunny.png", alt: "맑은 날씨 일러스트" },
    sw011: { src: "img/irasutoya/snow.png", alt: "눈 오는 날씨 일러스트" },
    sw012: { src: "img/irasutoya/rain.png", alt: "비 오는 날씨 일러스트" },

    tm001: { src: "img/undraw/calendar.svg", alt: "어제 날짜 일러스트" },
    tm002: { src: "img/undraw/calendar.svg", alt: "오늘 날짜 일러스트" },
    tm003: { src: "img/irasutoya/morning.png", alt: "아침 일러스트" },
    tm004: { src: "img/undraw/calendar.svg", alt: "내일 날짜 일러스트" },
    tm005: { src: "img/undraw/calendar.svg", alt: "오후 시간 일러스트" },
    tm006: { src: "img/undraw/calendar.svg", alt: "정오 시간 일러스트" },
    tm007: { src: "img/irasutoya/night.png", alt: "밤 일러스트" },
    tm008: { src: "img/undraw/calendar.svg", alt: "저녁 시간 일러스트" },
    tm009: { src: "img/undraw/up_to_date.svg", alt: "현재 시간 일러스트" },
    tm010: { src: "img/undraw/up_to_date.svg", alt: "현재 시간 일러스트" },
    tm011: { src: "img/undraw/up_to_date.svg", alt: "지금 일러스트" },
    tm012: { src: "img/undraw/calendar.svg", alt: "다가오는 날짜 일러스트" },
    tm013: { src: "img/undraw/calendar.svg", alt: "지난 날짜 일러스트" },

    ct001: { src: "img/flags/tn.svg", alt: "튀니지 국기" },
    ct002: { src: "img/flags/sy.svg", alt: "시리아 국기" },
    ct003: { src: "img/flags/eg.svg", alt: "이집트 국기" },

    kn001: { src: "img/undraw/personal_text.svg", alt: "인칭과 상태 변화 일러스트" },
    kn002: { src: "img/undraw/personal_text.svg", alt: "인칭과 상태 변화 일러스트" },
    kn003: { src: "img/undraw/personal_text.svg", alt: "인칭과 상태 변화 일러스트" },
    kn004: { src: "img/undraw/personal_text.svg", alt: "인칭과 상태 변화 일러스트" },
    kn005: { src: "img/undraw/personal_text.svg", alt: "인칭과 상태 변화 일러스트" },
    kn006: { src: "img/undraw/up_to_date.svg", alt: "현재 상태 일러스트" },
    kn007: { src: "img/undraw/up_to_date.svg", alt: "현재 상태 일러스트" },
    kn008: { src: "img/undraw/up_to_date.svg", alt: "현재 상태 일러스트" },
    kn009: { src: "img/undraw/up_to_date.svg", alt: "현재 상태 일러스트" },
    kn010: { src: "img/undraw/up_to_date.svg", alt: "현재 상태 일러스트" }
  },
  sentences: {
    s001: { src: "img/irasutoya/student_boy.png", alt: "남학생 일러스트" },
    s002: { src: "img/irasutoya/student_girl.png", alt: "여학생 일러스트" },
    s003: { src: "img/undraw/personal_text.svg", alt: "남자 이름 소개 일러스트" },
    s004: { src: "img/undraw/personal_text.svg", alt: "여자 이름 소개 일러스트" },
    s005: { src: "img/flags/kr.svg", alt: "대한민국 국기" },
    s006: { src: "img/basic/good.svg", alt: "잘 지내는 상태 카드" },
    s007: { src: "img/basic/question.svg", alt: "상태 질문 카드" },
    s008: { src: "img/irasutoya/sunny.png", alt: "좋은 날씨 일러스트" },
    s009: { src: "img/irasutoya/book.png", alt: "책 일러스트" },
    s010: { src: "img/irasutoya/book.png", alt: "책 일러스트" },
    s011: { src: "img/undraw/documents.svg", alt: "펜과 책 일러스트" },
    s012: { src: "img/irasutoya/bag.png", alt: "가방을 든 사람 일러스트" },
    s013: { src: "img/irasutoya/room.png", alt: "방 일러스트" },
    s014: { src: "img/irasutoya/house.png", alt: "집 일러스트" },
    s015: { src: "img/irasutoya/water.png", alt: "물 한 잔 일러스트" },
    s016: { src: "img/irasutoya/book.png", alt: "책 일러스트" },
    s017: { src: "img/irasutoya/bag.png", alt: "가방 일러스트" },
    s018: { src: "img/family/father.svg", alt: "아버지 카드" },
    s019: { src: "img/family/mother.svg", alt: "어머니 카드" },
    s020: { src: "img/irasutoya/morning.png", alt: "아침 일러스트" },
    s021: { src: "img/irasutoya/spring.png", alt: "봄 일러스트" },
    s022: { src: "img/irasutoya/summer.png", alt: "여름 일러스트" },
    s023: { src: "img/irasutoya/autumn.png", alt: "가을 일러스트" },
    s024: { src: "img/irasutoya/winter.png", alt: "겨울 일러스트" }
  }
};
